# Absenteeism Project - Logistic Regression

In [59]:
import pandas as pd
import numpy as np

In [60]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed = data_preprocessed.drop(['Unnamed: 0'], axis=1)
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Create two classes... Moderately Absent & Excessively Absent

In [61]:
# take the median value of the 'Absenteeism Time in Hours' column and use it as a cut-off line

data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [62]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [63]:
data_preprocessed.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'], dtype=object)

In [64]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [65]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [66]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

### Extract the Inputs:

In [67]:
data_with_targets.iloc[:, 0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [68]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

### Scaling the inputs: Standardize the Data

In [69]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler() 


# subtract the mean and divide by the standard deviation from each point variablewise(featurewise)

In [70]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):


    def __init__(self,columns,copy=True, with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self_columns = columns
        self.mean_ = None
        self.var = None 

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        return pd.concat([X_not_scaled], axis=1)

#this code will not standardize all inputs, but only the ones that we choose

In [71]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [ ]:
columns_to_scale = ['Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets']

In [12]:
# scaling mechanism
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

Whenever you obtain new data, you will know that the standardization information is contained in 'absenteeism_scaler'

In [13]:
# Standardize
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-1.72957821, -0.57735027, -0.09298136, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-1.72462949, -0.57735027, -0.09298136, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-1.71968077, -0.57735027, -0.09298136, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.71968077,  1.73205081, -0.09298136, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [ 1.72462949, -0.57735027, -0.09298136, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [ 1.72957821, -0.57735027, -0.09298136, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [14]:
scaled_inputs.shape

(700, 15)

## Split the data into Train & Test and shuffle:

### Import the relevant module

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
# Split
train_test_split(scaled_inputs, targets)

[array([[ 1.4969883 , -0.57735027, -0.09298136, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.77942366, -0.57735027, -0.09298136, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.56662863, -0.57735027, -0.09298136, ..., -0.44798003,
         -0.01928035,  1.12666297],
        ...,
        [-1.03675718, -0.57735027, -0.09298136, ..., -0.44798003,
          0.88046927, -0.58968976],
        [ 0.32908999, -0.57735027, -0.09298136, ..., -0.44798003,
          0.88046927,  0.26848661],
        [ 1.19511628, -0.57735027, -0.09298136, ...,  2.23224237,
         -0.91902997, -0.58968976]]),
 array([[ 0.79426982,  1.73205081, -0.09298136, ..., -0.44798003,
         -0.91902997,  1.12666297],
        [ 1.68503972, -0.57735027, -0.09298136, ..., -0.44798003,
          0.88046927,  2.8430157 ],
        [-0.15093601,  1.73205081, -0.09298136, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [ 0.24991044, -0.57735027, -0.09298136, ..., -

In [17]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [18]:
print(x_train.shape, y_test.shape)
print(x_test.shape, y_test.shape)

(560, 15) (140,)
(140, 15) (140,)


## Logistic Regression with sklearn
    Training the Model:

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [20]:
reg = LogisticRegression()

reg.fit(x_train, y_train)

C:\Users\Owner\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
reg.score(x_train, y_train)

0.7821428571428571

### Manually check the accuracy:

In [22]:
model_outputs = reg.predict(x_train)

model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [23]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [24]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [25]:
np.sum(model_outputs == y_train)

438

In [26]:
model_outputs.shape[0]

560

In [27]:
np.sum(model_outputs == y_train)

438

In [28]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7821428571428571

### Extracting the Intercept and Coefficients from a Logistic Regression

In [29]:
reg.intercept_

array([-0.22039248])

In [30]:
reg.coef_

array([[-0.24385951,  2.10053023,  0.34726806,  1.5486538 ,  1.33785787,
         0.12995442, -0.06819169,  0.7025177 , -0.05734919, -0.18697433,
        -0.08296111,  0.32817202, -0.09601388,  0.36826206, -0.31781541]])

In [31]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Unnamed: 0', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month Value', 'Day of the Week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [33]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table


Feature Name  Coefficient
0                Unnamed: 0    -0.243860
1                  Reason_1     2.100530
2                  Reason_2     0.347268
3                  Reason_3     1.548654
4                  Reason_4     1.337858
5               Month Value     0.129954
6           Day of the Week    -0.068192
7    Transportation Expense     0.702518
8          Distance to Work    -0.057349
9                       Age    -0.186974
10  Daily Work Load Average    -0.082961
11          Body Mass Index     0.328172
12                Education    -0.096014
13                 Children     0.368262
14                     Pets    -0.317815

In [38]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()

summary_table

Feature Name  Coefficient
0                 Intercept    -0.220392
1                 Intercept    -0.220392
2                Unnamed: 0    -0.243860
3                  Reason_1     2.100530
4                  Reason_2     0.347268
5                  Reason_3     1.548654
6                  Reason_4     1.337858
7               Month Value     0.129954
8           Day of the Week    -0.068192
9    Transportation Expense     0.702518
10         Distance to Work    -0.057349
11                      Age    -0.186974
12  Daily Work Load Average    -0.082961
13          Body Mass Index     0.328172
14                Education    -0.096014
15                 Children     0.368262
16                     Pets    -0.317815

## Interpreting the Coefficients

In [39]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

summary_table

Feature Name  Coefficient  Odds_ratio
0                 Intercept    -0.220392    0.802204
1                 Intercept    -0.220392    0.802204
2                Unnamed: 0    -0.243860    0.783598
3                  Reason_1     2.100530    8.170501
4                  Reason_2     0.347268    1.415196
5                  Reason_3     1.548654    4.705132
6                  Reason_4     1.337858    3.810871
7               Month Value     0.129954    1.138776
8           Day of the Week    -0.068192    0.934081
9    Transportation Expense     0.702518    2.018829
10         Distance to Work    -0.057349    0.944264
11                      Age    -0.186974    0.829465
12  Daily Work Load Average    -0.082961    0.920387
13          Body Mass Index     0.328172    1.388428
14                Education    -0.096014    0.908451
15                 Children     0.368262    1.445221
16                     Pets    -0.317815    0.727737

In [43]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature Name  Coefficient  Odds_ratio
3                  Reason_1     2.100530    8.170501
5                  Reason_3     1.548654    4.705132
6                  Reason_4     1.337858    3.810871
9    Transportation Expense     0.702518    2.018829
15                 Children     0.368262    1.445221
4                  Reason_2     0.347268    1.415196
13          Body Mass Index     0.328172    1.388428
7               Month Value     0.129954    1.138776
10         Distance to Work    -0.057349    0.944264
8           Day of the Week    -0.068192    0.934081
12  Daily Work Load Average    -0.082961    0.920387
14                Education    -0.096014    0.908451
11                      Age    -0.186974    0.829465
0                 Intercept    -0.220392    0.802204
1                 Intercept    -0.220392    0.802204
2                Unnamed: 0    -0.243860    0.783598
16                     Pets    -0.317815    0.727737

*Note: A feature is not particularly important if:*
- its coefficient is around 0
- if its odds ratio is around 1

*A weight(coefficient) of 0 implies that no matter the feature*
*value, we will multiply it by 0(in the model)*

*For a unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio(1 = no change)*