# Absenteeism Project - Logistic Regression

In [63]:
import pandas as pd
import numpy as np

In [64]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

data_preprocessed.head()

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         0         1            7   
1           1         0         0         0         0            7   
2           2         0         0         0         1            7   
3           3         1         0         0         0            7   
4           4         0         0         0         1            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### Create two classes... Moderately Absent & Excessively Absent

In [65]:
# take the median value of the 'Absenteeism Time in Hours' column and use it as a cut-off line

data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [66]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [67]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         0         1            7   
1           1         0         0         0         0            7   
2           2         0         0         0         1            7   
3           3         1         0         0         0            7   
4           4         0         0         0         1            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0

## A comment on the targets

In [68]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [69]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)
data_with_targets.head()

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         0         1            7   
1           1         0         0         0         0            7   
2           2         0         0         0         1            7   
3           3         1         0         0         0            7   
4           4         0         0         0         1            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Extract the Inputs:

In [70]:
data_with_targets.iloc[:, 0:14]

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0             0         0         0         0         1            7   
1             1         0         0         0         0            7   
2             2         0         0         0         1            7   
3             3         1         0         0         0            7   
4             4         0         0         0         1            7   
..          ...       ...       ...       ...       ...          ...   
695         695         1         0         0         0            5   
696         696         1         0         0         0            5   
697         697         1         0         0         0            5   
698         698         0         0         0         1            5   
699         699         0         0         0         1            5   

     Day of the Week  Transportation Expense  Distance to Work  Age  \
0                  1                     289                36   33   
1                  1                     118                13   50   
2                  2                     179                51   38   
3                  3                     279                 5   39   
4                  3                     289                36   33   
..               ...                     ...               ...  ...   
695                2                     179                22   40   
696                2                     225                26   28   
697                3                     330                16   28   
698                3                     235                16   32   
699                3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  
0                    239.554               30          0         2  
1                    239.554               31          0         1  
2                    239.554               31          0         0  
3                    239.554               24          0         2  
4                    239.554               30          0         2  
..                       ...              ...        ...       ...  
695                  237.656               22          1         2  
696                  237.656               24          0         1  
697                  237.656               25          1         0  
698                  237.656               25          1         0  
699                  237.656               25          0         1  

[700 rows x 14 columns]

In [71]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

### Scaling the inputs: Standardize the Data

In [72]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()
# subtract the mean and divide by the standard deviation from each point variablewise(featurewise)

In [73]:
# scaling mechanism
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

Whenever you obtain new data, you will know that the standardization information is contained in 'absenteeism_scaler'

In [74]:
# Standardize
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-1.72957821, -0.57735027, -0.09298136, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-1.72462949, -0.57735027, -0.09298136, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-1.71968077, -0.57735027, -0.09298136, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.71968077,  1.73205081, -0.09298136, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [ 1.72462949, -0.57735027, -0.09298136, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [ 1.72957821, -0.57735027, -0.09298136, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [75]:
scaled_inputs.shape

(700, 15)

## Split the data into Train & Test and shuffle:

### Import the relevant module

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
# Split
train_test_split(scaled_inputs, targets)

[array([[ 0.58642351, -0.57735027, 10.75484387, ..., -0.44798003,
          0.88046927,  0.26848661],
        [ 1.69493716,  1.73205081, -0.09298136, ..., -0.44798003,
          0.88046927, -0.58968976],
        [ 0.27465405, -0.57735027, -0.09298136, ...,  2.23224237,
         -0.01928035,  0.26848661],
        ...,
        [-0.72498772, -0.57735027, -0.09298136, ..., -0.44798003,
         -0.01928035,  3.70119207],
        [-0.53198758, -0.57735027, -0.09298136, ..., -0.44798003,
          0.88046927, -0.58968976],
        [ 1.27924454, -0.57735027, -0.09298136, ..., -0.44798003,
          0.88046927, -0.58968976]]),
 array([[ 0.45775675, -0.57735027, -0.09298136, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 0.55673118,  1.73205081, -0.09298136, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-1.39306514, -0.57735027, -0.09298136, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [ 1.44255236, -0.57735027, -0.09298136, ..., -

In [78]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [79]:
print(x_train.shape, y_test.shape)
print(x_test.shape, y_test.shape)

(560, 15) (140,)
(140, 15) (140,)


## Logistic Regression with sklearn
    Training the Model:

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [81]:
reg = LogisticRegression()

reg.fit(x_train, y_train)

C:\Users\Owner\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [82]:
reg.score(x_train, y_train)

0.7821428571428571

### Manually check the accuracy:

In [83]:
model_outputs = reg.predict(x_train)

model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [84]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [85]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [86]:
np.sum(model_outputs == y_train)

438

In [87]:
model_outputs.shape[0]

560

In [88]:
np.sum(model_outputs == y_train)

438

In [89]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7821428571428571

### Extracting the Intercept and Coefficients from a Logistic Regression

In [90]:
reg.intercept_

array([-0.22039248])

In [91]:
reg.coef_

array([[-0.24385951,  2.10053023,  0.34726806,  1.5486538 ,  1.33785787,
         0.12995442, -0.06819169,  0.7025177 , -0.05734919, -0.18697433,
        -0.08296111,  0.32817202, -0.09601388,  0.36826206, -0.31781541]])

In [0]:
feature_name = unscaled_inputs.columns.values
feature_name

In [97]:
summary_table = pd.Dataframe(columns = ['Feature Name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table


AttributeError: module 'pandas' has no attribute 'Dataframe'